version: '3.9'
services:
  api:
    build: ./api
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./api:/app
  web:
    build: ./client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
    environment:
      - VITE_API_URL=http://localhost:8000
